### ISSUE TITLE
Hubot sends multiple packets to api upon 2+ vm creations

### ISSUE THREAD

**Issue by quickjp2** [EMC-Underground/vsphere-commands#1]
The second time the first vm packet is sent along with several copies of the new vm.

**Comment by quickjp2** [comment]
Hubot will respond twice after the mem answer, then three times after the next, then four after the next, finally sending off 5 different json packets.

**Comment by quickjp2** [comment]
Refactored the code in a new branch, but now the issue is the callback function passed to the respond object for a question is being called once when declared and then again when actually responding.
![hubotresponseerror](https://cloud.githubusercontent.com/assets/1683549/12041657/248de2a8-ae28-11e5-841b-994e104860e5.PNG)

**Comment by quickjp2** [comment]
![hubotresponseerrorp2](https://cloud.githubusercontent.com/assets/1683549/12042094/94365cbc-ae2c-11e5-956a-e5fa55abb8fb.PNG)

**Comment by quickjp2** [comment]
The two pictures show that the callback function is being called once before the user response and once after. I purposely prevented the next call from being executed until the dual call issue is fixed.

**Comment by heckj** [comment]
hey @quickjp2 

I think you're misreading the error - the issue isn't that askQuestion is getting called multiple times (looks like it's designed very much to be called recursively), but that it can't find the reference to itself:

    ReferenceError: askQuestion is not defined

**Comment by quickjp2** [comment]
Indeed! It is meant to be recursive. But the problem is not that it's not recursing (if that's even a word). The issue is that recursive function is being called before I even respond to it.
